layout_spectrum: 0.4886895
typography_spectrum: 0.7100256
color:
  saturation: 0.3362955
  lightness: 0.919118
  brandStrength: 0.789353
  rhythmicContrast: 0.8973595
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: 'TheCats!'
