name: 'TheCats!'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59354
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#868690'
    - '#9d9d9d'
    - '#635a5f'
    - '#dee4e4'
    - '#967143'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.8973595
purpose: []
