analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.74499
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#d7ecfd'
    - '#050908'
    - '#6a8b3c'
    - '#32312d'
    - '#b9ab42'
  lightness: 0.8125
purpose: []
favicon: null
name: The Cats!
typography_spectrum: 0.91425
